/* Achievement - Lista global de conquistas
- _id - Identificador único da conquista
- name - Nome da conquista
- type - Valores possíveis:
• "xp" → baseado em pontos de experiência acumulados.
• "streak" → baseado em dias consecutivos com hábitos feitos.
• "count" → baseado no número total de hábitos concluídos.
- threshold - Valor necessário para desbloquear a conquista, de acordo com o type.
Exemplos:
• type: "xp", threshold: 100 → conquista ao atingir 100 XP.
• type: "streak", threshold: 7 → conquista por 7 dias consecutivos.
• type: "count", threshold: 50 → conquista por 50 hábitos concluídos.
- icon - URL ou nome de um ícone/imagem da conquista */
